### ISSUE TITLE
Event format has changed

### ISSUE THREAD

**Issue by buckmaxwell** [asottile/api-gateway-v2-to-wsgi#15]
Hi -- I attempted to use this library yesterday and wanted to point out some issues that I encountered. These were both easy fixes and I like the lightweight nature of this library. I hesitated to open a PR or fork because I saw this was updated as recently as yesterday so figured it must be working for somebody.

1. [This line](https://github.com/asottile/api-gateway-v2-to-wsgi/blob/4bc3216a9840ec89c41bf0af188ce16411191a6c/api_gateway_v2_to_wsgi.py#L65) causes an issue when body is set to None on the event (can't call encode None on line 69)

```py
body_b = body.encode() if body else b'' # will do the trick on 69
```

2. The event structure seems to have changed in other ways too.
    + rawPath is now path
    + rawQueryString may not be present
    + request context no longer has an http key, now has an identity key
    + headers are not called multiValueHeaders
    + there are a lot of these type of changes, I won't enumerate them all
    

If others are running into the same issue I'll open a PR with the changes; if some are still using this successfully (perhaps for older versions of API v2?) I can open a PR that supports looking for keys in both formats.

**Comment by asottile** [comment]
are you sure you're not using the v1 format?

**Comment by asottile** [comment]
yeah you're using the v1 format of api gateway (which has `body: null`) -- note that this library is called "api-gateway-v2" and intentionally does not use the v1 format

**Comment by asottile** [comment]
from the aws docs [here's a sample v1 request](https://github.com/awsdocs/aws-lambda-developer-guide/blob/8c08f832a4f2df60f5338cb68b1635fb42cc0bcd/sample-apps/nodejs-apig/event.json) and [here's a sample v2 request](https://github.com/awsdocs/aws-lambda-developer-guide/blob/8c08f832a4f2df60f5338cb68b1635fb42cc0bcd/sample-apps/nodejs-apig/event-v2.json)

**Comment by buckmaxwell** [comment]
lol. oops. I guess I'll fix that

**Comment by asottile** [comment]
if you're working with terraform, there's an example included in this repository: https://github.com/asottile/api-gateway-v2-to-wsgi/blob/master/testing/example/tf/lambda_sample_app.tf

otherwise you can probably map this to whatever system and/or the console
