### ISSUE TITLE
Document difference to Zappa

### ISSUE THREAD

**Issue by untitaker** [asottile/api-gateway-v2-to-wsgi#4]
Just found this in my newsfeed. Is there a reason I would use this over e.g. https://github.com/Miserlou/Zappa (or at least over the parts of Zappa that deal with translation to WSGI)?

**Comment by asottile** [comment]
zappa appears to be an entire suite of deployment tools and other things and comes with [a hefty list of dependencies](https://github.com/Miserlou/Zappa/blob/master/requirements.in) (this library also has zero dependencies) -- it also appears to be django specific and won't work with other web frameworks.

here's zappa's ~equivalent module to what this library does: https://github.com/Miserlou/Zappa/blob/master/zappa/wsgi.py

it also appears they don't support api gateway v2 (only v1) (https://github.com/Miserlou/Zappa/issues/2099)
