### ISSUE TITLE
Can't set multiple cookies

### ISSUE THREAD

**Issue by adamchainz** [asottile/api-gateway-v2-to-wsgi#9]
I just finished upgrading my similar package [apig-wsgi](https://pypi.org/project/apig-wsgi/) to support v2. I used this library as reference. On the way I spotted a bug - the `set-cookie` header in responses *does* work, but if a response sets more than one cookie, you can only have one header, so the other cookies will get dropped. You need to pull the cookie headers out into the `cookies` return array.

Additionally ths library isn't returning the full response object (doc'd at bottom of [this page](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.response)), I'm not sure if there are potential issues there e.g. api gateway may try and infer if response content is base64 encoded (not documented ofc).

**Comment by asottile** [comment]
closing => archiving
